PROGRAM MPIGPUAWARE

USE HIPFORT
USE ISO_C_BINDING
USE MPI
 
IMPLICIT NONE

REAL, ALLOCATABLE         :: H_SEND (:), H_RECV (:)

INTEGER :: IREQ_RECV, IREQ_SEND
INTEGER :: ISTATUS (MPI_STATUS_SIZE)
INTEGER :: ISIZE, IERROR_R,IERROR_S,IERROR_B,IERROR
INTEGER :: IRANK, IRANKP, IRANKN
INTEGER, PARAMETER :: ISIZEDATA=16
INTEGER     :: COMPTEUR
INTEGER(C_INT)::NUM_CARTE,FLAGS

CALL MPI_INIT (ierror)

CALL MPI_COMM_RANK (MPI_COMM_WORLD, IRANK, IERROR)
CALL MPI_COMM_SIZE (MPI_COMM_WORLD, ISIZE, IERROR)

!!write (0,*) "using hipInit, result : ", hipInit(flags)
!!write (0,*) "using hipSetDevice, result : ", hipSetDevice(IRANK)
!!write (0,*) "using hipGetDevice, result : ", hipGetDevice(NUM_CARTE)
!!print *, "Rank ",IRANK ," running on GPU number ",num_carte

ALLOCATE (H_RECV (ISIZEDATA))
ALLOCATE (H_SEND (ISIZEDATA))

CALL RANDOM_NUMBER (H_SEND)

PRINT *, "Rank",irank," valeur initialisation h_send" , H_SEND(1:10)

IRANKP = MODULO (IRANK-1, ISIZE)
IRANKN = MODULO (IRANK+1, ISIZE)

do COMPTEUR=1,ISIZEDATA
  H_SEND(COMPTEUR) = H_SEND(COMPTEUR)+irank
  H_RECV(COMPTEUR) = -1.0
enddo

PRINT *, "Rank",irank," valeur apres ajout rank h_send",H_SEND(1:10)

!!$omp target data map (tofrom:H_RECV, H_SEND)

PRINT *, " HOST DATA (USE_DEVICE) "

!!$OMP TARGET DATA USE_DEVICE_ADDR (H_RECV)
CALL MPI_IRECV (H_RECV,ISIZEDATA,MPI_REAL,IRANKP, 1001, MPI_COMM_WORLD, IREQ_RECV, &
             & IERROR_R)
!!$OMP END TARGET DATA

CALL MPI_BARRIER (MPI_COMM_WORLD,IERROR_B)

!!$OMP TARGET DATA USE_DEVICE_ADDR (H_SEND)
CALL MPI_ISEND (H_SEND,ISIZEDATA,MPI_REAL,IRANKN, 1001, MPI_COMM_WORLD, IREQ_SEND, &
             & IERROR_S)
!!$OMP END TARGET DATA

CALL MPI_WAIT (IREQ_RECV,istatus,ierror)
CALL MPI_WAIT (IREQ_SEND,istatus,ierror)

!!$OMP END TARGET DATA

PRINT *, "Rank",IRANK, " received  ==> ", H_RECV (1:10)
PRINT *, "Rank",IRANK, " sent ==> ", H_SEND(1:10)

DEALLOCATE (H_SEND)
DEALLOCATE (H_RECV)

PRINT *, "IERROR_S",IERROR_S,"IERROR_R",IERROR_R,"IERROR_B",IERROR_B

CALL MPI_BARRIER (MPI_COMM_WORLD,ierror)

PRINT *, "FINALIZE"


CALL MPI_FINALIZE(ierror)

END PROGRAM MPIGPUAWARE
